name: Update README

on:
  schedule:
    - cron: 19 18 * * *

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update README
        run: node index.js

      - name: Commit changes
        run: |
          git config --global user.name "Minh Monmen"
          git config --global user.email "minhpq331@gmail.com"
          git add README.md
          git commit -m "Update README"
          git push origin main